# Generated by Django 5.1 on 2024-08-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=10, unique=True, verbose_name='C.I.')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('diplomados', models.PositiveIntegerField(default=0, verbose_name='Diplomados')),
                ('especialidades', models.PositiveIntegerField(default=0, verbose_name='Especialidades')),
                ('maestrias', models.PositiveIntegerField(default=0, verbose_name='Maestrias')),
                ('doctorados', models.PositiveIntegerField(default=0, verbose_name='Doctorados')),
                ('asistencia_programas', models.PositiveIntegerField(default=0, verbose_name='Asistencias')),
                ('antiguedad', models.PositiveIntegerField(default=0, verbose_name='Antiguedad')),
                ('experiencia', models.PositiveIntegerField(default=0, verbose_name='Experiencia')),
                ('docente', models.PositiveIntegerField(default=0, verbose_name='Docente')),
                ('articulos', models.PositiveIntegerField(default=0, verbose_name='Articulos')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
            ],
            options={
                'db_table': 'calificacion',
            },
        ),
    ]
